/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Countdown: typeof import('./src/components/Countdown/Countdown.vue')['default']
    H5BackTransition: typeof import('./src/components/H5BackTransition/H5BackTransition.vue')['default']
    JIcon: typeof import('./src/components/JIcon/JIcon.vue')['default']
    JImage: typeof import('./src/components/JImage/JImage.vue')['default']
    JSearch: typeof import('./src/components/JSearch/JSearch.vue')['default']
    Navbar: typeof import('./src/components/Navbar/Navbar.vue')['default']
    PlayController: typeof import('./src/components/PlayController/PlayController.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Song: typeof import('./src/components/Song/Song.vue')['default']
    Songlist: typeof import('./src/components/Songlist/Songlist.vue')['default']
    Subtitle: typeof import('./src/components/Subtitle/Subtitle.vue')['default']
  }
}
