/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Image: typeof import('./src/components/Image/Image.vue')['default']
    Navbar: typeof import('./src/components/Navbar/Navbar.vue')['default']
    Playlist: typeof import('./src/components/Playlist/Playlist.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Song: typeof import('./src/components/Song/Song.vue')['default']
    Songlist: typeof import('./src/components/Songlist/Songlist.vue')['default']
    Subtitle: typeof import('./src/components/Subtitle/Subtitle.vue')['default']
  }
}
